language: java
jdk:
  - openjdk17
branches:
  only:
    - main

# Travis CI Server's Home
cache:
  - directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r alzzaipo
  - mkdir -p deploy
  - mv alzzaipo.zip deploy/alzzaipo.zip
  
before_install:
  - chmod +x gradlew

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: alzzaipo-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - csct3434@gmail.com
