package com.alzzaipo.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    DUPLICATED_EMAIL(HttpStatus.CONFLICT),
    ACCOUNT_ID_DUPLICATED(HttpStatus.CONFLICT),
    INVALID_MEMBER_ID(HttpStatus.BAD_REQUEST),
    INVALID_STOCKCODE(HttpStatus.BAD_REQUEST),
    INVALID_KAKAO_AUTH_CODE(HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_KAKAO_ACCESS_TOKEN(HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_PORTFOLIO(HttpStatus.BAD_REQUEST),
    INVALID_ACCOUNT_ID(HttpStatus.UNAUTHORIZED),
    EXPIRED_EMAIL_AUTHENTICATION_CODE(HttpStatus.BAD_REQUEST),
    INVALID_EMAIL_VERIFICATION_CODE(HttpStatus.UNAUTHORIZED),
    INVALID_EMAIL_FORMAT(HttpStatus.BAD_REQUEST),
    AUTHENTICATION_CODE_SEND_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    ILLEGAL_ARGUMENT_EXCEPTION(HttpStatus.BAD_REQUEST),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    BAD_REQUEST(HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD_FORMAT(HttpStatus.BAD_REQUEST),
    UNVERIFIED_EMAIL(HttpStatus.UNAUTHORIZED),
    NULL_PASSED(HttpStatus.BAD_REQUEST),
    INVALID_ACCOUNT_PASSWORD(HttpStatus.UNAUTHORIZED),
    INVALID_NEW_PASSWORD(HttpStatus.BAD_REQUEST),
    INVALID_SOCIAL_ACCOUNT(HttpStatus.BAD_REQUEST);

    private final HttpStatus httpStatus;
}
