# default
spring:
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: local
    import: application-local-config.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: application-prod-config.yml
---
spring:
  config:
    activate:
      on-profile: test
    import: application-local-config.yml



