# default profile
spring:
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: local
    import: secrets/application-common-config.yml, secrets/application-local-config.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: secrets/application-common-config.yml, secrets/application-prod-config.yml