spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ipo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    hidden-method:
      filter:
        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace