spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    hidden-method:
      filter:
        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:secrets/local_keystore.p12
    key-store-password: ${ssl.password}