spring:
  profiles:
    active: prod
  mail:
    host: smtp.daum.net
    port: 465
    username: ${smtp.email}
    password: ${smtp.password}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 30000
server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: local
    import: secrets/application-common-config.yml, secrets/application-local-config.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: secrets/application-common-config.yml, secrets/application-prod-config.yml